name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the artifact to deploy"
        required: false
        default: "dist"
        type: string
    # secrets:
    #     some-secret:
    #       required: false
    outputs:
      result:
        description: "Status of the deployment"
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.set-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: echo "set-result=success" >> $GITHUB_OUTPUT
